apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS tododb;
    GRANT ALL PRIVILEGES ON tododb.* TO 'root'@'%';
    FLUSH PRIVILEGES;
  PYTHONUNBUFFERED: "1"
