apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: mysql
type: Opaque
data:
  DB_NAME: dG9kb2Ri
  MYSQL_USER: YXBwdXNlcg==
  MYSQL_PASSWORD: YXBwcGFzc3dvcmQ=
  MYSQL_DATABASE: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==
  MYSQL_ROOT_PASSWORD: bXktc2VjcmV0LXB3
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
